# Mise à jour automatique des dépendances
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Python pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Grouper les mises à jour mineures
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
      production-dependencies:
        patterns:
          - "httpx*"
          - "twitchio*"
          - "openai*"
