# ===== SERDABOT CONFIGURATION EXAMPLE =====
# 
# 📌 INSTRUCTIONS :
# 1. Créer le dossier local : mkdir -p ../SerdaBot-local/config
# 2. Copier ce fichier : cp src/config/config.example.yaml ../SerdaBot-local/config/config.yaml
# 3. Remplir les vraies valeurs (tokens, clés API, etc.)
# 4. Lancer le bot : ./start_bot.sh (détecte automatiquement la config locale)
#
# ⚠️  NE JAMAIS COMMITER config.yaml avec de vraies clés !

bot:
  language: "fr"                            # Langue par défaut ("en" ou "fr")
  name: "your_bot_name"                     # Nom d'utilisateur Twitch du bot (login, pas display name)
  channel: "your_channel_name"              # Nom du channel Twitch (sans @)
  
  # === LLM Configuration (OPTIONAL) ===
  # Le bot fonctionne parfaitement avec ou sans LLM local
  # Si LM Studio n'est pas disponible → mode fallback automatique
  llm:
    enabled: auto                           # auto (détection automatique) | true (force) | false (désactive)
    fallback_mode: fun                      # fun (répliques humoristiques) | silent (neutre) | minimal (emoji)
  
  model_path: "src/model"                   # Chemin du dossier du modèle local
  model_file: "your-model.gguf"             # Nom du fichier GGUF du modèle
  model_type: "openai"                      # Type de modèle ("mistral", "llama", "openai", etc.)
  openai_model: "gpt-3.5-turbo"             # Modèle OpenAI à utiliser
  use_gpu: true                             # Activer l'accélération GPU (true/false)
  gpu_layers: 50                            # Nombre de layers GPU
  cooldown: 10                              # Cooldown entre réponses (en secondes)
  model_endpoint: http://127.0.0.1:1234/v1/chat/completions  # Endpoint LM Studio
  api_url: http://127.0.0.1:1234/v1/chat/completions         # API LM Studio
  model_name: "qwen2.5-3b-instruct"         # Nom du modèle (Qwen2.5-3B-Instruct-Q4_K_M recommandé)
  model_timeout: 10                         # Timeout requêtes modèle (secondes)
  max_tokens_ask: 120                       # Max tokens mode ASK (réponses détaillées)
  max_tokens_chill: 60                      # Max tokens mode CHILL (conversations)
  temperature_ask: 0.4                      # Temperature ASK (factuel)
  temperature_chill: 0.7                    # Temperature CHILL (créatif)
  log_ia: true                              # Activer logs IA (debug)
  debug: true                               # Verbose output (debug)
  translation: libretranslate               # Service de traduction ("model" ou "libretranslate")
  reset_cache_on_boot: false                # Reset cache au démarrage (default: false)
  kofi_url: "https://ko-fi.com/your_username"       # URL Ko-fi pour donations
  donation_message: "☕ Merci pour le support ! Tu peux soutenir [YourName] ici : {kofi_url} 💜"
  connect_message: "Coucou ☕"                       # Message de connexion Twitch (vide = désactivé)

  enabled_commands:
    - game
    - chill
    - ask
    - trad

openai:
  api_key: "sk-proj-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  # Clé API OpenAI (depuis platform.openai.com)

twitch:
  token: "oauth:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"   # Token OAuth Twitch (depuis twitchtokengenerator.com)
  client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"     # Client ID Twitch (dev.twitch.tv)
  client_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Client Secret Twitch
  bot_id: "123456789"                                # User ID du bot Twitch

igdb:
  client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"     # Client ID IGDB (dev.twitch.tv)
  client_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Client Secret IGDB

rawg:
  api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"       # Clé API RAWG (rawg.io/apidocs)

# ===== Rate Limiting & Performance =====
rate_limiting:
  # User cooldowns (anti-spam)
  user_cooldown: 10                    # Secondes entre messages par user
  max_requests_per_user_hour: 20       # Limite anti-spam par user/heure
  max_concurrent_users: 4              # Max users simultanés
  
  # Cleanup (optimisation mémoire)
  cleanup_interval: 600                # Nettoyage toutes les 10min
  max_idle_time: 3600                  # Supprimer users inactifs > 1h
  
  # LLM endpoint failure handling (retry intelligent)
  llm_retry_delay: 5                   # Premier retry après 5s d'échec
  llm_backoff_multiplier: 2            # Backoff exponentiel (5s → 10s → 20s)
  llm_backoff_max: 300                 # Backoff max 5min entre retries
  llm_reset_on_success: true           # Reset compteur échecs si succès
  
  # Health check (heartbeat - optionnel en prod 24/7)
  health_check_enabled: false          # Activer pour monitoring proactif
  health_check_interval: 30            # Secondes entre pings santé endpoint
  health_check_timeout: 2              # Timeout ping santé
  health_check_failures_threshold: 3   # Échecs consécutifs avant marquer "down"
  
  # External APIs rate limits
  wikipedia_rate_limit: 1.0            # 1 requête/sec (Wikipedia)
  igdb_rate_limit: 4.0                 # 4 requêtes/sec (Twitch API)
