"""
⚙️ Configuration Système Quantique - KissBot V1

Configuration spécialisée pour les phénomènes quantiques.
Ajout à config.yaml principal pour activer comportements quantiques.
"""

# Configuration à ajouter dans config.yaml

quantum_cache:
  # TTL États collapsed (vérifiés par utilisateurs)
  ttl_verified_seconds: 86400        # 24h - États permanents
  
  # TTL États en superposition (non-vérifiés)  
  ttl_unverified_seconds: 1800       # 30min - Particules virtuelles
  
  # Limite superposition simultanée (principe incertitude)
  max_superposition_states: 3        # Max 3 états par clé
  
  # Activation système intrication
  entanglement_enabled: true
  
  # Logs détaillés phénomènes quantiques
  debug_quantum: false

quantum_games:
  # Seuil auto-intrication (genres similaires)
  auto_entangle_threshold: 0.8       # Confiance min pour auto-lien
  
  # Boost confiance sur confirmation utilisateur
  confirmation_confidence_boost: 0.3  # +30% confiance
  
  # Nombre max suggestions affichées
  max_suggestions: 3
  
  # Cache file spécialisé jeux quantiques
  cache_file: "cache/quantum_games.json"
  
  # Cleanup automatique (décohérence)
  auto_cleanup_interval: 3600        # 1h entre nettoyages auto

# Nouveaux rate limits pour commandes quantiques
rate_limits:
  quantum_commands:
    collapse_cooldown: 5              # 5s entre !collapse par user
    observe_cooldown: 2               # 2s entre !observe par user
    entangle_cooldown: 30             # 30s entre !entangle (mods only)
    decoherence_cooldown: 300         # 5min entre !qclean global

# Système permissions quantiques
quantum_permissions:
  # Qui peut déclencher collapse
  collapse_allowed: ["everyone"]
  
  # Qui peut créer intrications  
  entangle_allowed: ["mods", "broadcaster"]
  
  # Qui peut déclencher décohérence manuelle
  decoherence_allowed: ["mods", "broadcaster"]
  
  # Limite créations superposition par user/heure
  user_superposition_limit: 10